language: rust
sudo: required
rust:
  - stable
  - beta
  - nightly
env:
  - OPENEXR_DIR=/usr/local ILMBASE_DIR=/usr/local OPENEXR_LIB_SUFFIX=2_2
before_install:
  - wget https://github.com/openexr/openexr/archive/v2.2.0.tar.gz -O openexr2.2.tar.gz
  - tar xzf openexr2.2.tar.gz
  - pushd openexr-2.2.0/IlmBase && cmake -DCMAKE_C_FLAGS="-fPIC" -DCMAKE_CXX_FLAGS="-fPIC" -DCMAKE_INSTALL_PREFIX=/usr/local ./ && make && sudo make install && popd
  - pushd openexr-2.2.0/IlmBase && rm CMakeCache.txt && cmake -DCMAKE_C_FLAGS="-fPIC" -DCMAKE_CXX_FLAGS="-fPIC" -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_SHARED_LIBS=OFF ./ && make && sudo make install && popd
  - pushd openexr-2.2.0/OpenEXR && cmake -DCMAKE_C_FLAGS="-fPIC" -DCMAKE_CXX_FLAGS="-fPIC" -DCMAKE_INSTALL_PREFIX=/usr/local -DILMBASE_PACKAGE_PREFIX=/usr/local -DBUILD_SHARED_LIBS=OFF ./ && make && sudo make install && popd
