[workspace]
members = ["openexr-sys"]

[package]
name = "openexr"
version = "0.1.0"
authors = ["Nathan Vegdahl <cessen@cessen.com>"]
repository = "https://github.com/cessen/openexr-rs"
readme = "README.md"
license = "MIT"
keywords = ["OpenEXR"]

[lib]
name = "openexr"
path = "src/lib.rs"

[dependencies]
libc = "0.2"

[dependencies.openexr-sys]
path = "openexr-sys"
