name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Every-other month, to make sure new Rust
    # releases don't break things.
    - cron: '15 12 5 1,3,5,7,9,11 *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test-stable:
    name: Build and test, Rust-stable
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install libopenexr24 libopenexr-dev libilmbase24 libilmbase-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
      - uses: actions-rs/cargo@v1
        with:
          command: test

  build-and-test-beta:
    name: Build and test, Rust-beta
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install libopenexr24 libopenexr-dev libilmbase24 libilmbase-dev
      - uses: ryankurte/action-apt@v0.2.0
        with:
          # Install OpenEXR
          packages: libopenexr24 libopenexr-dev libilmbase24 libilmbase-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: beta
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
      - uses: actions-rs/cargo@v1
        with:
          command: test
